version: "3.1"

services:
    backend:
        build:
            context: ./ecommerce/
            dockerfile: DockerFile.dev
        
        command: python manage.py runserver 0.0.0.0:8002

        volumes: 
            - ./ecommerce:/backend
        ports:
            # - "8000:8000"
            - "8002:8002"
        expose: 
            # - 8000
            - 8002
        networks: 
            - ecommerce
        depends_on: 
            - db
            - redis_db
        restart: always

    db:
        image: mysql
        command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
        ports:
          - "3307:3306"
        volumes: 
            - mysql_data:/var/lib/mysql
        environment:
           MYSQL_DATABASE: 'commerce-fm'
           MYSQL_USER: 'saijal'
           MYSQL_PASSWORD: 'root'
           MYSQL_ROOT_PASSWORD: 'root'
        networks: 
            - ecommerce

    
    redis_db:
        image: redis
        # expose: 
        #     - "6379"
        networks: 
            - ecommerce

    celery:
        build: 
            context: ./ecommerce/
            dockerfile: DockerFile.dev
        volumes:
            - ./ecommerce:/backend
        command: celery -A ecommerce worker -l info
        links:
            - redis_db
        networks: 
            - ecommerce
        restart: on-failure

volumes: 
    mysql_data:
        driver: local
    

networks:
    ecommerce:
        driver: bridge
