# Generated by Django 3.0 on 2020-10-11 12:08

import Offer.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category for Offers',
                'verbose_name_plural': 'Categories for Offers',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('starts_from', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('big_banner_image', models.ImageField(upload_to=Offer.models.big_banner_image_name_change)),
                ('small_banner_image', models.ImageField(upload_to=Offer.models.small_banner_image_name_change)),
                ('category', models.ManyToManyField(related_name='offers_category', to='Offer.OfferCategory')),
            ],
            options={
                'verbose_name': 'Special Offer',
                'verbose_name_plural': 'Special Offers',
                'ordering': ['starts_from'],
                'permissions': (('participate_in_offer', 'Can participate in offers.'),),
            },
        ),
    ]
