# Generated by Django 3.0 on 2020-11-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0002_offer_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discounts',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
