# Generated by Django 3.0 on 2020-10-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Referral', '0004_vendorblock_vendorkey_vendorreferral_vendorreward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorblock',
            old_name='user',
            new_name='vendor',
        ),
    ]
