# Generated by Django 3.0 on 2020-10-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Referral', '0005_auto_20201011_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='previous_has',
            new_name='previous_hash',
        ),
        migrations.RenameField(
            model_name='vendorblock',
            old_name='previous_has',
            new_name='previous_hash',
        ),
    ]
