# Generated by Django 3.0 on 2020-10-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Searched Keyword',
                'verbose_name_plural': 'Searched Keywords',
            },
        ),
    ]
