# Generated by Django 3.0 on 2020-10-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverySystem', '0001_initial'),
        ('OrderAndDelivery', '0004_auto_20201015_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direct_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliverySystem.DeliveryPerson'),
        ),
    ]
