# Generated by Django 3.0 on 2020-10-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndDelivery', '0005_order_direct_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='any_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
