# Generated by Django 3.0 on 2020-10-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndDelivery', '0008_paymentmethods_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'ordering': ['-count'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='OrderAndDelivery.PaymentMethods'),
            preserve_default=False,
        ),
    ]
