# Generated by Django 3.0 on 2020-10-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndDelivery', '0009_auto_20201016_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
