# Generated by Django 3.0 on 2020-10-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndDelivery', '0014_auto_20201016_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_person_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_taken_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
