# Generated by Django 3.0 on 2020-10-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndDelivery', '0015_auto_20201016_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
