# Generated by Django 3.0 on 2020-10-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndDelivery', '0016_order_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
