# Generated by Django 3.0 on 2020-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndDelivery', '0017_auto_20201016_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_reason',
            field=models.TextField(blank=True, help_text='Required when status=4 or Cancelled', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Delivered'), (4, 'Cancelled')], default=1),
        ),
    ]
