# Generated by Django 3.0 on 2020-10-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0003_vendor_phone'),
        ('OrderAndDelivery', '0018_auto_20201017_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Vendor.Vendor'),
            preserve_default=False,
        ),
    ]
