# Generated by Django 3.0 on 2020-10-11 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendor.Vendor'),
        ),
        migrations.CreateModel(
            name='SoftDeletedProducts',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted Product',
                'verbose_name_plural': 'Deleted Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Products.product',),
        ),
    ]
