# Generated by Django 3.0 on 2020-10-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20201014_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='market',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
