# Generated by Django 3.0 on 2020-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20201014_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketing',
            options={'verbose_name': 'Marketing', 'verbose_name_plural': 'Marketings'},
        ),
        migrations.AddField(
            model_name='marketing',
            name='added_by',
            field=models.BooleanField(choices=[(True, 'By Admin'), (False, 'By User')], default=False),
        ),
    ]
