# Generated by Django 3.0 on 2020-10-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20201014_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketing',
            options={'ordering': ['-count'], 'verbose_name': 'Marketing', 'verbose_name_plural': 'Marketings'},
        ),
    ]
